# Generated by Django 4.1.7 on 2023-03-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tache",
            name="last_date",
        ),
        migrations.AlterField(
            model_name="tache",
            name="duration",
            field=models.PositiveIntegerField(verbose_name="Durée (min)"),
        ),
        migrations.AlterField(
            model_name="tache",
            name="frequence_int",
            field=models.PositiveIntegerField(verbose_name="Fréquence (jours)"),
        ),
        migrations.AlterField(
            model_name="tache",
            name="tache_text",
            field=models.CharField(max_length=200, verbose_name="Intitulé"),
        ),
        migrations.CreateModel(
            name="SessionMenage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quand", models.DateField(verbose_name="Quand ?")),
                (
                    "real_duration",
                    models.PositiveIntegerField(verbose_name="Durée réelle (min)"),
                ),
                (
                    "tache",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taskmanager.tache",
                    ),
                ),
            ],
        ),
    ]
