# Generated by Django 4.1.7 on 2023-04-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0002_remove_tache_last_date_alter_tache_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessionmenage",
            options={"ordering": ("quand",)},
        ),
    ]
